version: "3.7"

volumes:
  grafana-storage:

services:
  groonga:
    image: groonga/groonga
    ports:
      - "10041:10041"

  groonga-prepare:
    build:
      context: dockerfiles/groonga-prepare
    depends_on:
      - groonga

  grafana:
    image: grafana/grafana:7.1.5
    volumes:
      - ./:/var/lib/grafana/plugins/groonga-datasource
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - groonga-prepare
