name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - run: yarn run grafana-toolkit plugin:sign
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
      - name: Get plugin information
        run: |
          GRAFANA_PLUGIN_ID=$(jq -r .id dist/plugin.json)
          GRAFANA_PLUGIN_VERSION=$(jq -r .info.version dist/plugin.json)
          GRAFANA_PLUGIN_TYPE=$(jq -r .type dist/plugin.json)
          GRAFANA_PLUGIN_ARTIFACT=${GRAFANA_PLUGIN_ID}-${GRAFANA_PLUGIN_VERSION}.zip
          GRAFANA_PLUGIN_ARTIFACT_CHECKSUM=${GRAFANA_PLUGIN_ARTIFACT}.md5

          echo "GRAFANA_PLUGIN_ID=${GRAFANA_PLUGIN_ID}" >> ${GITHUB_ENV}
          echo "GRAFANA_PLUGIN_VERSION=${GRAFANA_PLUGIN_VERSION}" >> ${GITHUB_ENV}
          echo "GRAFANA_PLUGIN_TYPE=${GRAFANA_PLUGIN_TYPE}" >> ${GITHUB_ENV}
          echo "GRAFANA_PLUGIN_ARTIFACT=${GRAFANA_PLUGIN_ARTIFACT}" >> ${GITHUB_ENV}
          echo "GRAFANA_PLUGIN_ARTIFACT_CHECKSUM=${GRAFANA_PLUGIN_ARTIFACT_CHECKSUM}" >> ${GITHUB_ENV}
      - name: Create package
        run: |
          mv dist ${GRAFANA_PLUGIN_ID}
          zip -r ${GRAFANA_PLUGIN_ARTIFACT} ${GRAFANA_PLUGIN_ID}
          md5sum ${GRAFANA_PLUGIN_ARTIFACT} > ${GRAFANA_PLUGIN_ARTIFACT_CHECKSUM}
          echo "GRAFANA_PLUGIN_CHECKSUM=$(cut -d' ' -f1 ${GRAFANA_PLUGIN_ARTIFACT_CHECKSUM})" >> ${GITHUB_ENV}
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - uses: actions/upload-release-asset@v1
        id: upload-plugin-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ env.GRAFANA_PLUGIN_ARTIFACT }}
          asset_name: ${{ env.GRAFANA_PLUGIN_ARTIFACT }}
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        id: upload-plugin-checksum-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ env.GRAFANA_PLUGIN_ARTIFACT_CHECKSUM }}
          asset_name: ${{ env.GRAFANA_PLUGIN_ARTIFACT_CHECKSUM }}
          asset_content_type: text/plain
      - name: Publish to grafana.com
        run: |
          echo Publish your plugin to grafana.com/plugins by opening a PR to https://github.com/grafana/grafana-plugin-repository with the following entry:
          echo
          ( \
            echo '{'; \
            echo '  "id": "${{ env.GRAFANA_PLUGIN_ID }}",'; \
            echo '  "type": "${{ env.GRAFANA_PLUGIN_TYPE }}",'; \
            echo '  "url": "https://github.com/${{ github.repository }}",'; \
            echo '  "versions": ['; \
            echo '    {'; \
            echo '      "version": "${{ env.GRAFANA_PLUGIN_VERSION }}",'; \
            echo '      "commit": "${{ github.sha }}",'; \
            echo '      "url": "https://github.com/${{ github.repository }}",'; \
            echo '      "download": {'; \
            echo '        "any": {'; \
            echo '          "url": "${{ steps.upload-plugin-asset.outputs.browser_download_url }}",'; \
            echo '          "md5": "${{ env.GRAFANA_PLUGIN_CHECKSUM }}"'; \
            echo '        }'; \
            echo '      }'; \
            echo '    }'; \
            echo '  ]'; \
            echo '}'; \
          ) | jq .
